<?php

namespace ContainerXcU2e13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddNewsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AddNews' shared autowired service.
     *
     * @return \App\Controller\AddNews
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AddNews.php';

        return $container->services['App\\Controller\\AddNews'] = new \App\Controller\AddNews();
    }
}
