#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainPage::index
addnews:
    path: /newseditor
    controller: App\Controller\NewsController::add
newsadded:
    path: /api/news
    controller: App\Controller\API\NewsAPI::news
news:
    path: /news/{page}
    controller: App\Controller\NewsController::index
    defaults:
        page: 0
    requirements:
        page: '\d+'
player:
    path: /api/player
    controller: App\Controller\API\PlayerAPI::players
town:
        path: /api/town
        controller: App\Controller\API\TownAPI::towns
realm:
    path: /api/realm
    controller: App\Controller\API\RealmAPI::realms