#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainPage::index
addnews:
    path: /newseditor
    controller: App\Controller\NewsController::add
newsadded:
    path: /newsAdd
    controller: App\Controller\NewsController::added
news:
    path: /news
    controller: App\Controller\NewsController::index