#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainPage::index
addnews:
    path: /newseditor
    controller: App\Controller\NewsController::add
newsadded:
    path: /api/news
    controller: App\Controller\API\NewsAPI::news
news:
    path: /news/{page<\d+>?1}
    controller: App\Controller\NewsController::index
player:
    path: /api/player
    controller: App\Controller\API\PlayerAPI::init
town:
        path: /api/town
        controller: App\Controller\API\TownAPI::init
realm:
    path: /api/realm
    controller: App\Controller\API\RealmAPI::init