#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainPage::index
    #schemes:    [https]
addnews:
    path: /newseditor
    controller: App\Controller\NewsController::add
    #schemes:    [https]
newsadded:
    path: /api/news
    controller: App\Controller\API\NewsAPI::news
    #schemes:    [https]
news:
    path: /news/{page<\d+>?0}
    controller: App\Controller\NewsController::index
    #schemes:    [https]
player:
    path: /api/player
    controller: App\Controller\API\PlayerAPI::init
    # schemes:    [https]
town:
    path: /api/town
    controller: App\Controller\API\TownAPI::init
    # schemes:    [https]
realm:
    path: /api/realm
    controller: App\Controller\API\RealmAPI::init
    # schemes:    [https]
about:
    path: /about
    controller: App\Controller\SimpleController::about
    #schemes:    [https]
help:
    path: /help
    controller: App\Controller\SimpleController::help
    #schemes:    [https]
profile:
    path: /profile/{userid?}
    controller: App\Controller\SimpleController::profile
    #schemes:    [https]
customitem:
    path: /api/item
    controller: App\Controller\API\CustomItemAPI::init
    #schemes:    [https]
playerbyname:
    path: /api/playerbyname
    controller: App\Controller\API\PlayerAPI::getObjectbyName
    #schemes:    [https]
specnews:
    path: /specnews/{newsid<\d+>?0}
    controller: App\Controller\NewsController::specific
