#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\MainPage::index
addnews:
    path: /newseditor
    controller: App\Controller\NewsController::add
newsadded:
    path: /api/news
    controller: App\Controller\API\NewsAPI::news
news:
    path: /news/{page<\d+>?0}
    controller: App\Controller\NewsController::index
player:
    path: /api/player
    controller: App\Controller\API\PlayerAPI::init
town:
    path: /api/town
    controller: App\Controller\API\TownAPI::init
realm:
    path: /api/realm
    controller: App\Controller\API\RealmAPI::init
about:
    path: /about
    controller: App\Controller\SimpleController::about
admin:
    path: /admin
    controller: App\Controller\SimpleController::admin
help:
    path: /help
    controller: App\Controller\SimpleController::help
ban:
    path: /ban
    controller: App\Controller\SimpleController::ban
profile:
    path: /profile/{userid?}
    controller: App\Controller\SimpleController::profile
customitem:
    path: /api/item
    controller: App\Controller\API\CustomItemAPI::init
playerbyname:
    path: /api/playerbyname
    controller: App\Controller\API\PlayerAPI::getObjectbyName