<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9noLSSD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9noLSSD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9noLSSD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9noLSSD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9noLSSD\App_KernelDevDebugContainer([
    'container.build_hash' => '9noLSSD',
    'container.build_id' => '11ddeb2a',
    'container.build_time' => 1619959068,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9noLSSD');
