<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerICNg1dS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerICNg1dS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerICNg1dS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerICNg1dS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerICNg1dS\App_KernelDevDebugContainer([
    'container.build_hash' => 'ICNg1dS',
    'container.build_id' => '87f9c9bf',
    'container.build_time' => 1620122612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerICNg1dS');
